[package]
name = "nbtrs"
version = "0.1.1"
authors = ["Andrew Chin <achin@eminence32.net>"]
edition = "2018"

[dependencies]
flate2 = "1"
byteorder = "1"

[[example]]
name = "nbt_dump"
path = "examples/nbt_dump.rs"
